version: "3"
services:
  build:
      image: node:16
      user: node
      volumes:
        - .:/app
      working_dir: '/app'
      command: 'npm start'

  web:
    image: nginx:1.19
    ports:
      - 8081:80
    volumes:
      - ./docs:/usr/share/nginx/html:ro

  browserstack:
    image: nginx:1.19
    ports:
      - 8082:80
    volumes:
      - ./browserstack/site:/usr/share/nginx/html:ro

  unit_test:
    image: node:16
    user: node
    volumes:
      - .:/app
    working_dir: '/app'
    command: 'npm run test:unit'
    depends_on:
      - web

  browserstack_test:
    image: node:16
    user: node
    environment:
      BROWSERSTACK_USERNAME: ${BROWSERSTACK_USERNAME}
      BROWSERSTACK_ACCESS_KEY: ${BROWSERSTACK_ACCESS_KEY}
      DEV_BROWSERSTACK_TEST: ${DEV_BROWSERSTACK_TEST}
    volumes:
      - .:/app
    working_dir: '/app'
    command: 'npm run test:browserstack'
    depends_on:
      - browserstack

