version: "3"
services:
  build:
    image: node:20
    user: node
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
    working_dir: "/app"
    command: "npm start"

  web:
    image: nginx:1.19
    container_name: test.container
    volumes:
      - ./browserstack/site:/usr/share/nginx/html:ro

  web-subdomain:
    image: nginx:1.19
    container_name: sub.test.container
    volumes:
      - ./browserstack/site:/usr/share/nginx/html:ro

  test:
    image: node:20
    user: node
    volumes:
      - .:/app
    working_dir: "/app"
    command: "npm run test:unit"

  browserstack_test:
    image: node:20
    user: node
    environment:
      - BROWSERSTACK_USERNAME=${BROWSERSTACK_USERNAME}
      - BROWSERSTACK_ACCESS_KEY=${BROWSERSTACK_ACCESS_KEY}
      - DEV_BROWSERSTACK_TEST=${DEV_BROWSERSTACK_TEST}
    volumes:
      - .:/app
    working_dir: "/app"
    command: "npm run test:browserstack"
    depends_on:
      - web
      - web-subdomain
