version: "3"
services:
  build:
      image: node:16
      user: node
      environment:
        - NODE_ENV=${NODE_ENV}
      volumes:
        - .:/app
      working_dir: '/app'
      command: 'npm start'

  web:
    image: nginx:1.19
    ports:
      - 8080:80
    volumes:
      - ./browserstack/site:/usr/share/nginx/html:ro

  unit_test:
    image: node:16
    user: node
    volumes:
      - .:/app
    working_dir: '/app'
    command: 'npm run test:unit'

  browserstack_test:
    image: node:16
    user: node
    volumes:
      - .:/app
    working_dir: '/app'
    command: 'npm run test:browserstack'
    depends_on:
      - web

