#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

MAIN_BRANCH=main

build() {
    echo "Build dist folder..."
    docker-compose run build npm run build
}

checkDiff() {
    echo "Check modification..."
    git status
    if [[ `git status --porcelain` ]]
    then
        echo "--------------------------------------------------------------------------------------------------"
        echo "ERROR: dist folder does not seem up to date. Make sure you built the last version of assets before merged in ${MAIN_BRANCH}"
        echo "--------------------------------------------------------------------------------------------------"

        git reset --merge
        exit 1;
    fi
}

checkBeforeMerge()  {
    local branch_name=$(git branch | grep '*' | sed 's/* //')

    if [[ "$branch_name" == "$MAIN_BRANCH" ]]
    then
        build
        checkDiff
    fi
}

checkBeforeMerge